.github/workflows/deploy.yml, build.sh, index.html
=> [Test] #7 - 배포세팅을 위한 파일추가+OG오류수정

src/App.jsx, src/pages/loginPage/WelcomePage.jsx, src/pages/loginPage/WelcomePage.styled.js, src/styles/global.js, src/styles/theme.js
스크롤 문제 해결이 안돼서 다시한번 시도했습니다. 
웰컴페이지 그라데이션이 반대로되어있어 그것도 수정했습니다. 
- #11
=> [Fix] #11 - 스크롤 다시한번 수정

src/pages/loginPage/WelcomePage.styled.js
기존 수정한 코드가 배포시 차이가없어서 vh값대신 --vh를 만든 기존의 코드에 아직 그냥 vh로 써져있던 마진값들까지 전부     height: calc(var(--vh, 1vh) * 수치); 의 형태로 변경하였습니다. 
이거도 안되면 추후에 수정하겠습니다... 
- #11
=> [Fix] #11 -스크롤문제 기존마진 vh값들 까지 전부변경

src/pages/loginPage/WelcomePage.styled.js
현재 크롬에서도 처음보이는 화면에 원하는 페이지가 다 뜨게까지는 고쳤는데 스크롤이되고 밑에 흰박스가 좀 나오는거만 수정하고자합니다. 
```
//화면 전체를 감싸는 래퍼 +배경색
export const Wrapper = styled.section`
display: flex;
flex-direction: column;
/* height: 100vh; //뷰포트 높이에 따라 반응 */
height: calc(var(--vh, 1vh) * 100);
overflow: hidden; /* 스크롤 방지 */
background: ${({ theme }) => theme.colors.bgGradient};
//background-color는 단색배경에만 적용됨
box-sizing: border-box;
padding: 0 5.56vw; /* 좌우 360 800기준으로 잡음 4.5vh*/
`;
```
min-height: calc(var(--vh, 1vh) * 100);이었던 기존코드를 height로 변경
- ex) #3
=> [Fix] #11 - 스크롤 마지막수정

src/layout/DefaultLayout.jsx
ㅠㅠ자꾸 하나씩 빼먹어서 디폴트레이아웃에는 vh로되어있어서 바꿨습ㄴ디ㅏ!!!
min-height: calc(var(--vh, 1vh) * 100);
- #11
=> [Fix] #11 - 디폴트레이아웃 수정을 안했다!

src/pages/loginPage/WelcomePage.jsx
지금까지 수정한거로도 계속 스크롤이 생겨서 body에서도 overflow hidden으로 스크롤 막아보기 
- #11
=> [Fix] #11 - body에서 강제로 스크롤막기추가

package-lock.json, package.json, src/apis/axiosInstance.js
api연결을 위한 axios 인스턴스를 생성했습니다. 
apis폴더에서 axiosInstance.js를 생성했습니다. 
api통신 되는것만 확인했습니다!
```
// src/api/axiosInstance.js
import axios from "axios";
const axiosInstance = axios.create({
baseURL: import.meta.env.VITE_BASE_URL,
});
export default axiosInstance;
```
이렇게 설정하면 API 호출 시마다 baseURL을 반복해서 지정할 필요 없이 axiosInstance를 불러와 간편하게 요청을 보낼 수 있습니다. 테스트용으로 임시로 작성했어요.
- #11
=> [Feature] #11 - api연결을 위한 axios 인스턴스 생성

src/assets/icons/back.svg, src/components/Header.jsx, src/hooks/useCustomNavigate.jsx, src/layout/DefaultLayout.jsx, src/pages/adminAttPage/AdminAttManagePage.jsx, src/pages/adminAttPage/AdminAttManagePage.styled.js, src/pages/adminAttPage/AdminAttPage.jsx, src/pages/adminAttPage/AdminAttPage.styled.js, src/pages/adminAttPage/AdminAttRegisterPage.jsx, src/pages/adminAttPage/AdminAttRegisterPage.styled.js, src/pages/loginPage/WelcomePage.jsx, src/pages/loginPage/WelcomePage.styled.js, src/router.jsx, src/styles/theme.js
지금까지 작업한거 올립니다! 
컴포넌트 폴더에 헤더 만들어뒀고 운영진 출석페이지 
이렇게 만들고 라우터 연결해놨어요 
용하는(Extension) 부분에 대한 설명-->
- #27
=> [Feature] #27 - 헤더추가 운영진 출석파일 추가

src/components/MainHeader.jsx, src/pages/lionAttPage/LionAttNum.jsx, src/pages/lionAttPage/LionAttNum.styled.js, src/pages/schMainPage/SchMainPage.jsx, src/pages/schMainPage/SchMainPage.styled.js, src/router.jsx
아기사자 출석 코드 입력 페이지 구현했습니다
- ex) #35
=> [Feature] 출석 코드 입력 페이지 구현

src/pages/lionAttPage/LionAttInfoPage.jsx, src/pages/lionAttPage/LionAttInfoPage.styled.js
아기사자 출석 정보 확인 페이지 수정했습니다
- 전체적으로 가로 길이가 짧은 것 수정
- 버튼 하단에 고정
- ex) #41
=> [Fix] #41 - 아기사자 출석 정보 확인 페이지 사이즈와 버튼 위치 수정

src/router.jsx
=> [Fix] #44 - 경로 에러 수정

vercel.json
버셀에서 경로로 접근하면 404오류 뜨는거해결 
vercel.json파일 생성하고 
```
{
"rewrites": [{ "source": "/(.*)", "destination": "/" }]
}
```
이 코드 추가하면
vercel.json 설정을 추가하면, 서버가 모든 경로 요청을 index.html로 리디렉트하게 됩니다.
즉, /adminAtt, /login, /signup 등 어떤 경로로 접근하더라도, 서버는 index.html 파일을 반환합니다.
그런 다음 React Router가 클라이언트 측에서 올바르게 라우팅을 처리합니다.
이러한 방법으로 해결됨 
-  #27
=> [Chore] #27 - 버셀 404오류 수정

src/pages/accountPage/LoginPage.jsx
로그인 API연결했습니다.
로그인시 세션 id 잘 들어가있습니다. 
- #62
=> [Feature] #62 - 로그인 API연결

src/components/schBoard/Board.jsx, src/components/schBoard/Board.styled.js, src/components/schBoard/BoardInfo.jsx, src/pages/boardPage/BeBoardPage.jsx, src/pages/boardPage/BoardPage.styled.js, src/pages/boardPage/DefaultBoardPage.jsx, src/pages/boardPage/FeBoardPage.jsx, src/pages/boardPage/JoinBoardPage.jsx, src/pages/boardPage/LionBoardPage.jsx, src/pages/boardPage/NotiBoardPage.jsx, src/pages/boardPage/PmBoardPage.jsx
전체 커뮤니티의 게시판별 목록 페이지 api 연결했습니다
전체 커뮤니티의 게시글이 게시판 구분없이 한번에 넘어오고 있어서 필터링해서 사용했습니다
추후에 추가할 내용입니다
* 목록 페이지에서 익명이 아닌 경우에 작성자의 id가 아닌 username이 나타나기
* 사진이 있는 경우에 함께 나타나기
- ex) #80
=> [Feature] #80 - 전체 커뮤니티의 게시판별 목록 페이지 api 연결

src/components/lionAttPage/LionAttCard.jsx, src/components/lionAttPage/LionAttCard.styled.js, src/pages/adminAttPage/AdminAttPage.jsx, src/pages/lionAttPage/LionAttInfoPage.styled.js, src/pages/lionAttPage/LionAttPage.jsx, src/pages/lionAttPage/LionAttPage.styled.js, src/router.jsx
api연결하려면 아기사자 출석페이지 디자인을 추가적으로 해야돼서 이것만했습니다. 
status 값에 따라 변경됩니다. 
- #88
=> [Fix] #88 - 아기사자 출석상세 변경된 ui구현

src/components/lionAttPage/LionAttCard.styled.js, src/hooks/useCustomNavigate.jsx, src/pages/lionAttPage/LionAttPage.jsx, src/pages/schMainPage/SchMainPage.jsx
배포에 반영하려고 중간에 올립니다 라우터 LionAttCard인데 LionAttcard인가 이렇게돼있던거 같아요 그외에 isStaff로 출석 메인 api연결하고 나중에 커스텀훅 useNavigation수정할거 주석에 적어놓는거 등등했음 
-  #88
=> [Refactor] #88 - 배포를위한 라우터 대문자수정,출석메인 api연결 isStaff

src/components/post/Comments.jsx, src/components/post/Input.jsx, src/pages/commuPage/CommuMainPage.jsx, src/pages/mainPostPage/BePostPage.jsx, src/pages/mainPostPage/DefaultPostPage.jsx, src/pages/mainPostPage/FePostPage.jsx, src/pages/mainPostPage/JoinPostPage.jsx, src/pages/mainPostPage/LionPostPage.jsx, src/pages/mainPostPage/NotiPostPage.jsx, src/pages/mainPostPage/PmPostPage.jsx
전체 커뮤니티 댓글 작성 api 연결했습니다
- ex) #80
=> [Feature] #80 - 전체 커뮤니티 댓글 작성 api 연결

src/pages/accountPage/VerificationPage.jsx, src/pages/accountPage/VerificationPage.styled.js
멋사 회원 인증 사진 첨부하면 파일명 나타나도록 수정했습니다
- ex) #110
=> [Fix] #110 - 멋사 회원 인증 사진 첨부하면 파일명 나타나도록 수정

src/hooks/useUserVerification.js, src/pages/schMainPage/SchMainPage.jsx
학교 인증 반영되도록 훅 수정했습니다
```
import useUserVerification from '@hooks/useUserVerification';
export const SchMainPage = () => {
const verification = useUserVerification ();
return (
<S.Wrapper>
{verification !== "approved" && <Back />}
</S.Wrapper>
);
};
```
이렇게 작성하시면 됩니다!
- ex) #80
=> [Fix] #80 - 학교 인증 반영되도록 훅 수정

src/components/post/Content.jsx, src/components/schBoard/SchContent.jsx, src/pages/schBoardPage/SchAllBoardPage.jsx, src/pages/schBoardPage/SchQnaBoardPage.jsx, src/pages/schPostPage/QnAPostPage.jsx, src/pages/schPostPage/SchDefaultPostPage.jsx, src/router.jsx
학교 커뮤니티 게시글 api 연결하는 중입니다
- ex) #80
=> [Feature] #80 - 학교 커뮤니티 게시글 api 연결하는 중

src/components/post/Content.jsx, src/components/post/PostingBox.jsx, src/pages/mainPostPage/BePostPage.jsx, src/pages/mainPostPage/DefaultPostPage.jsx, src/pages/mainPostPage/FePostPage.jsx, src/pages/mainPostPage/JoinPostPage.jsx, src/pages/mainPostPage/LionPostPage.jsx, src/pages/mainPostPage/NotiPostPage.jsx, src/pages/mainPostPage/PmPostPage.jsx, src/pages/mainPostingPage/BePostingPage.jsx, src/pages/mainPostingPage/DefaultPostingPage.jsx, src/pages/mainPostingPage/FePostingPage.jsx, src/pages/mainPostingPage/JoinPostingPage.jsx, src/pages/mainPostingPage/LionPostingPage.jsx, src/pages/mainPostingPage/NotiPostingPage.jsx, src/pages/mainPostingPage/PmPostingPage.jsx
전체 커뮤니티 게시글 수정 api 연결했습니다
- ex) #80
=> [Feature] #80 - 전체 커뮤니티 게시글 수정 api 연결

src/components/adminAttManage/AttCodeTimer.jsx, src/components/adminAttRegister/AdminAttPost.jsx, src/pages/adminAttPage/AdminAttPage.styled.js, src/pages/lionAttPage/LionAttInfoPage.jsx, src/pages/lionAttPage/LionAttPage.jsx
QA항목들 수정했습니다.
1. 아기사자 출석,출석 정보페이지에 새로고침 버튼 추가했습니다
2. 운영진 출석관리페이지에서 타이머가 결석시간부터 되는게아니라 지각시간부터 되는문제, 타이머가 끝났을때 빨간색으로 00:00이 표시되는게 아닌 초록색으로 돌아오는 문제 해결했습니다.
3. 아기사자 출석 정보페이지에서 아직 출석을 할 수 있는 시간이어도 이미 출석했으면 이미 출석하였습니다로 글씨가 바뀌고 출석이 다시 안되게 수정했습니다. 
4. 운영진 출석 등록페이지에서 날짜와 시간을 따로 입력안해도 기본값으로 현재시간과 현재날짜로 설정되게 하였습니다. 
- #121
=> [Fix] #121 - QA항목들 수정 아기사자출석,운영진출석 등등

src/components/MainHeader.jsx, src/components/adminAttManage/AttCard.jsx, src/pages/accountPage/WelcomePage.jsx, src/pages/myPage/MyPage.jsx, src/pages/myPage/MyPage.styled.js
1.출석카드 폰트 지워졌어서 다시 적용
2. 메인헤더, 마이페이지 프로필 검정색 border지웠습니다. 
3. 현재 로그인하고나서 웰컴페이지로 가게되면 로그인이 됐는데 다시로그인하려고 처리가 돼서 403오류가 뜨고있어 웰컴페이지에서 로그인된 사람인지체크하고 로그인 됐으면 main으로 보내게 수정했습니다. 
- #121
=> [Fix] #121 -일반 로그인 api수정 + 디자인수정

src/pages/chatPage/ChatPage.jsx
채팅 로드되거나 새로고침할때 스크롤이 가장 하단으로 오게 수정 
가장 아래 채팅이 보이게 스크롤 하단으로 설정
- #121
=> [Fix] #121 - 채팅 로드될때 스크롤 아래로 오게 수정

src/components/post/Comments.jsx, src/components/post/Input.jsx, src/components/schBoard/Board.jsx, src/components/schBoard/SchContent.jsx, src/pages/mainPostPage/BePostPage.jsx, src/pages/mainPostPage/DefaultPostPage.jsx, src/pages/mainPostPage/FePostPage.jsx, src/pages/mainPostPage/JoinPostPage.jsx, src/pages/mainPostPage/LionPostPage.jsx, src/pages/mainPostPage/NotiPostPage.jsx, src/pages/mainPostPage/PmPostPage.jsx, src/pages/schBoardPage/SchAllBoardPage.jsx, src/pages/schBoardPage/SchQnaBoardPage.jsx, src/pages/schPostPage/QnAPostPage.jsx, src/pages/schPostPage/SchDefaultPostPage.jsx, src/pages/schPostingPage/QnAPostinPage.jsx, src/pages/schPostingPage/SchDefaultPostingPage.jsx, src/router.jsx
학교 커뮤니티의 질문 게시판 api 연결했습니다
이제 글 작성, 수정, 삭제, 댓글 가능합니다
제목에 트랙 구분 추가했습니다
댓글에 익명 번호가 추가되었습니다
- ex) #125
=> [Feature] #125 - 학교 커뮤니티의 질문 게시판 api 연결

src/components/post/Input.jsx, src/components/schBoard/SchContent.jsx, src/pages/myPage/MyCommentPage.jsx, src/pages/schBoardPage/SchNotiBoardPage.jsx, src/pages/schMainPage/SchMainPage.jsx, src/pages/schPostPage/SchNotiPostPage.jsx, src/pages/schPostingPage/SchNotiPostingPage.jsx, src/router.jsx
학교 커뮤니티의 공지사항 api 연결했습니다
- 학교 운영진인 경우에만 글 작성 버튼 보이도록 했습니다
- 학교 메인 화면의 헤더에 보이는 학교명을 사용자의 학교명에서 받아오도록 수정했습니다
- ex) #125
=> [Feature] #125 - 학교 커뮤니티의 공지사항 api 연결

src/pages/accountPage/WelcomePage.jsx
이미 카카오 로그인을 통해 로그인한 상태에서 다시 카카오 로그인을 시도할 경우 main 페이지로 이동하도록 코드 수정했습니다
- ex) #125
=> [Fix] #125 - 카카오 로그인 api 수정

package-lock.json, src/components/post/Content.jsx, src/components/schBoard/Board.jsx, src/pages/accountPage/WelcomePage.jsx
커뮤니티 목록 페이지 404 뜨는 에러 수정했습니다
#125
=> [Fix] #125 - 커뮤니티 목록 페이지 404 뜨는 에러 수정

src/components/BoardPost.jsx, src/components/MainHeader.jsx, src/components/mainPage/PopularPost.jsx, src/components/myPage/MyPagePost.jsx, src/components/post/Comments.jsx, src/components/post/Content.jsx, src/components/post/Content.styled.js, src/components/post/PostingBtn.jsx, src/components/schBoard/BoardInfo.jsx, src/components/schBoard/SchContent.jsx, src/pages/mainPostPage/BePostPage.jsx, src/pages/mainPostPage/DefaultPostPage.jsx, src/pages/mainPostPage/FePostPage.jsx, src/pages/mainPostPage/JoinPostPage.jsx, src/pages/mainPostPage/LionPostPage.jsx, src/pages/mainPostPage/NotiPostPage.jsx, src/pages/mainPostPage/PmPostPage.jsx, src/pages/mainPostingPage/DefaultPostingPage.jsx, src/pages/mainPostingPage/NotiPostingPage.jsx, src/pages/schBoardPage/SchAllBoardPage.jsx, src/pages/schBoardPage/SchNotiBoardPage.jsx, src/pages/schBoardPage/SchQnaBoardPage.jsx, src/pages/schPostPage/QnAPostPage.jsx, src/pages/schPostPage/SchDefaultPostPage.jsx, src/pages/schPostPage/SchNotiPostPage.jsx
커뮤니티에서 게시글과 댓글 작성자의 사진 보이도록 구현했습니다
모든 커뮤니티의 게시글과 댓글에 사용자의 프로필 이미지 추가 했습니다
익명이 아니고 사용자가 프로필을 설정한 경우에만 이미지 나타나고, 아니라면 기본 이미지가 나타납니다
그리고 게시글 작성 직후에는 -1분 전에 작성한 게시글이라고 화면에 나타났었는데, 0분 전이라고 뜨도록 수정했습니다
- #125
=> [Feature] #125 - 커뮤니티에서 게시글과 댓글 작성자의 사진 보이도록 구현

src/components/post/Comments.jsx, src/pages/mainPostPage/DefaultPostPage.jsx, src/pages/myPage/MyPostPage.jsx, src/pages/myPage/MyScrapPage.jsx, src/pages/schBoardPage/SchQnaBoardPage.jsx, src/pages/schBoardPage/SchQnaBoardPage.styled.js, src/pages/schPostPage/QnAPostPage.jsx, src/router.jsx
학교 커뮤니티의 질문게시판에 트랙 필터링 드롭다운 추가했습니다
그리고 코드 합치면서 커뮤니티 코드 일부가 사라져서 전체 커뮤니티의 자유게시판 수정 기능이 작동하지 않았는데, 코드 다시 추가해서 이 부분도 수정했습니다
- #125
=> [Feature] #125 - 학교 커뮤니티의 질문게시판에 트랙 필터링 드롭다운 추가

src/components/chat/ChatMember.jsx, src/components/chat/ChatStart.jsx, src/components/post/Comments.jsx, src/components/post/Content.jsx, src/components/schBoard/SchContent.jsx, src/pages/chatPage/ChatListPage.jsx, src/pages/chatPage/ChatListPage.styled.js, src/pages/chatPage/ChatPage.jsx, src/pages/chatPage/ChatPage.styled.js
채팅 api 연결했습니다
게시글 작성자나 댓글 작성자의 username을 클릭하면 채팅방으로 이동해서 채팅할 수 있게 구현했습니다
- #125
=> [Feature] #125 - 채팅 api 연결

src/pages/accountPage/WelcomePage.styled.js
웰컴페이지 16인치에서 글씨 줄넘김되는문제 수정 
기존에는 16인치 이상으로 화면가로길이가 넓어지면 글씨가 줄넘김 되었는데 이문제를 수정했음 
- #121
=> [Fix] #121 - 웰컴페이지 16인치 깨지는거 수정
